sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    # to make sure that the Google cloud CLI doesn't try to prompt us. 
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    # it's going to take the encrypted version of the file that's stored on Travis CI server and decrypt it
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    #install google cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
    #install kubectl inside of travis environment
  - gcloud components update kubectl
    # same as IAM of AWS. It tells Google SDK who we are and give access to our project inside google cloud
  - gcloud auth activate-service-account --key-file service-account.json
    # which google cloud project to use
  - gcloud config set project multi-k8s-303603
    # which zone to use
  - gcloud config set compute/zone us-central1-c
    #name of the cluster
  - gcloud container clusters get-credentials multi-cluster
    # login to docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # build an image to run the test against
  - docker build -t ashah1519/react-test -f ./client/Dockerfile.dev ./client

script:
    # run test
  - docker run -e CI=true ashah1519/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master